# Generated by Django 5.2.17 on 2026-09-23 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('refused', 'Refusée'), ('cancelled', 'Annulée')], default='pending', max_length=10, verbose_name='statut')),
                ('message', models.TextField(blank=True, max_length=500, verbose_name='message')),
                ('item_name', models.CharField(max_length=100, verbose_name="nom de l'objet")),
                ('requester_email', models.EmailField(blank=True, max_length=254, verbose_name='email du demandeur')),
                ('requester_phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone du demandeur')),
                ('owner_email', models.EmailField(blank=True, max_length=254, verbose_name='email du propriétaire')),
                ('owner_phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone du propriétaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='envoyée le')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='traitée le')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='items.item', verbose_name='objet')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL, verbose_name='demandeur')),
            ],
            options={
                'verbose_name': 'demande de contact',
                'verbose_name_plural': 'demandes de contact',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('item', 'requester'), name='unique_request_per_item')],
            },
        ),
    ]
