# Generated by Django 5.2.17 on 2026-09-23 20:12

import accounts.models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('position', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'quartier',
                'verbose_name_plural': 'quartiers',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('pseudo', models.CharField(blank=True, max_length=30, null=True, verbose_name='pseudo')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[accounts.models.validate_phone], verbose_name='téléphone')),
                ('share_email', models.BooleanField(default=True, verbose_name='partager mon email')),
                ('share_phone', models.BooleanField(default=False, verbose_name='partager mon téléphone')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='conditions acceptées le')),
                ('is_active', models.BooleanField(default=True, help_text='Décoché : compte suspendu ou supprimé, connexion impossible.', verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='administrateur')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='inscrit le')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.neighborhood', verbose_name='quartier')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('pseudo'), name='unique_pseudo_ci')],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
