# Generated by Django 5.2.17 on 2026-09-23 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('position', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ajouté le')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('search_text', models.TextField(default='', editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.category', verbose_name='catégorie')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'objet',
                'verbose_name_plural': 'objets',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
